/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * TiDev Titanium Mobile
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
package ti.bottomNavView;

import android.view.View;
import android.view.ViewGroup;

import com.google.android.material.bottomnavigation.BottomNavigationView;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.TiConfig;
import org.appcelerator.titanium.TiApplication;

import ti.modules.titanium.ui.TabGroupProxy;
import ti.modules.titanium.ui.ViewProxy;


@Kroll.module(name = "TiBottomNavView", id = "ti.bottomNavView")
public class TiBottomNavViewModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "TiBottomNavViewModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TiBottomNavViewModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
	}

	@Kroll.method
	public void addViewToBottomNav(Object customView, Object tabGroup) {
		if (tabGroup instanceof TabGroupProxy && customView instanceof ViewProxy) {
			TabGroupProxy tgp = (TabGroupProxy) tabGroup;
			View abstractTabGroup = tgp.getOrCreateView().getOuterView();
			BottomNavigationView bottomNav = (BottomNavigationView) ((ViewGroup) (abstractTabGroup.getParent())).getChildAt(1);

			ViewProxy vp = (ViewProxy) customView;
			bottomNav.addView(vp.getOrCreateView().getNativeView());
		}
	}

}

